### PR TITLE
Support rich text

### PR DESCRIPTION
**Pull request by LesterLyu**
## Support rich text
basic rich text support, update dependencies, add more style supports
[Old PR](https://github.com/dtjohnson/xlsx-populate/pull/180)

## New style support:
|Style Name|Type|Description|
| ------------- | ------------- | ----- |
|fontGenericFamily|`number`|1: Serif, 2: Sans Serif, 3: Monospace, |
|fontScheme|`string`|`'minor'`\|`'major'`\|`'none'` |

### CODE REVIEW

**Comment by Fauny** [comment]
@LesterLyu 
cannot work with new change.

I checked out branch beta/richtext from your fork, and tested with simple code, it did not works.

```js
"use strict";

const XlsxPopulate = require("./lib/XlsxPopulate");
XlsxPopulate.fromBlankAsync()
  .then(workbook => {
    workbook
      .sheet("Sheet1")
      .cell("A1")
      .value("This is neat!");

    let cell = workbook.sheet(0).cell("B1");
    cell.style('wrapText', true);
    cell
      .richText()
      .add("123\n", { italic: true, fontColor: "123456" })
      .add("456\r", { italic: true, fontColor: "654321" })
      .add("789\r\n", { italic: true, fontColor: "ff0000" })
      .add("10\n11\r12", { italic: true, fontColor: "00ff00" });

    workbook
      .sheet(0)
      .row(1)
      .height(100);

    return workbook.toFileAsync("./out.xlsx");
  })
  .catch(err => console.error(err));

```

**Comment by Fauny** [comment]
> @LesterLyu
> cannot work with new change.
> 
> I checked out branch beta/richtext from your fork, and tested with simple code, it did not works.
> 

I'v found that you just lost style() in the constructor:
```js
// RichText.js

// line:43 
            this.style(styles);  // add this to fix 
            this.value(value);  
```

**Comment by LesterLyu** [comment]
Thanks, I will commit tomorrow.

**Comment by dtjohnson** [comment]
This is a very nice PR! A few comments:

- You'll need unit tests/JSDoc for all functionality before we'll merge.
- For large updates like this we prefer to have E2E parse/generate tests to verify workbook integrity.
- I'm not sure I like the `richText` method on the cell. Shouldn't an instance of the `RichTexts` class just be the return value of the `value` method like all of the other values?
- It might be nice to have a helper method to just return the text of the rich text. A common use case we see is that you want just the concatenated string without the formatting. We could then have a similar helper method on `Cell`.
- How does this play with `SharedStrings`? I know rich text nodes exist in that schema as well.

**Comment by LesterLyu** [comment]
@dtjohnson Thanks for the suggestions.
 - I'll add unit tests/JsDoc.
 - I already wrote one e2e-parse test, will add e2e-generate test later.
- I'll remove the `richtext` method. Initially I don't want the user to import the `RichTexts` class to their own project, that's why I wrote `richtext` method.
- I'll add that helper function.
- As you see, rich text node is stored in `SharedStrings`:
I construct rich text node by calling [`toXml()`](https://github.com/dtjohnson/xlsx-populate/pull/190/files#diff-efa943ab9df71a06ead1d59092079b62R35) in `Richtexts.js` and in `cell.js` [`toXml()`](https://github.com/dtjohnson/xlsx-populate/pull/190/files#diff-4fd0fe446456815b64e9add5ee02475cR503) add: 
```js
else if (this._value instanceof RichTexts) {
                type = "s";
                text = this.workbook().sharedStrings().getIndexForString(this._value.toXml());
            }
```

**Comment by LesterLyu** [comment]
## changelog
- Add method `RichTexts.text` to get concatenated text of rich texts.
- Rename `RichText` class to `RichTextFragment`
- Add unit tests, update e2e-parse test
- Remove `Cell.richtext()` method, please use 
```js
const RichTexts = require('xlsx-Populate').RichTexts;
cell.value(new RichTexts(cell))
```
or,  see [this](https://github.com/LesterLyu/xlsx-populate/tree/richtext#new-richtextscell-node)
```
cell.value(new RichTexts())
```

**Comment by LesterLyu** [comment]
@dtjohnson @eddiecorrigall All tests have been added. Please review.

**Comment by dtjohnson** [comment]
Thanks for the updates. I'm not sure why you need to pass in an instance of the `RichTexts` class to `Cell.value` for the getter. The cell already knows its value is rich text, no?

**Comment by LesterLyu** [comment]
I understand you want `Cell.value()` return the concatenated string of rich texts, but how should people access the styles in the rich texts?

**Comment by dtjohnson** [comment]
No. I wanted Cell.value to return the rich text object. If folks want the
text they'd call Cell.value().text().

**Comment by LesterLyu** [comment]
It is returning the rich text object.

**Comment by LesterLyu** [comment]
Do you mean the code in the **Changelog**?
```js
const RichTexts = require('xlsx-Populate').RichTexts;
cell.value(new RichTexts(cell))
```
This tells folks how to set a cell from other types to richtext.

**Comment by dtjohnson** [comment]
I just find the setter syntax unintuitive:
```js
cell.value(new RichTexts(cell))
```
Seems weird to pass the cell reference to a method on itself. It's also super easy to pass a reference to a different cell, which would result in weird behavior.

Is it possible to eliminate the dependency on the cell from `RichTexts` altogether? So then the setter would just be:
```js
cell.value(new RichTexts())
```

The other benefit of this would be copying the rich text value from one cell to another:
```js
const rt = someCell.value(); // Instance of RichTexts
otherCell.value(rt); // Copy the value to another cell.
```
You'd probably want to make a copy when setting the value so that future changes don't affect both cells.

I'm also wondering if we should rename `RichTexts` to `RichText` to be consistent with the naming convention in Excel Interop.

**Comment by LesterLyu** [comment]
When a user wants to set rich texts with line breaks, in order to make excel display multiple lines, the cell's style has to have `wrapText = true`. This is why I ask a cell reference when initiate a rich text object. 

In order to eliminate the cell reference, I will need the users to set `cell.style('wrapText', true)` on their own. And, this will make the richtext copy easy.

I will rename `RichTexts` to `RichText`.

**Comment by dtjohnson** [comment]
You could set wrapText to true when Cell.value is called with a RichText
instance.

**Comment by LesterLyu** [comment]
Good idea.

**Comment by LesterLyu** [comment]
### Updated Rich Texts Usage
You can read/write rich texts to cells.
You can read and modify rich texts on an existing rich text cell:
```js
// assume A1 is a rich text cell
const RichText = require('xlsx-Populate').RichText;
const cell = workbook.sheet(0).cell('A1');
cell.value() instanceof RichText // returns true
const richtext = cell.value();
// get the concatenate text
richtext.text();

// loop through each rich text fragment
for (let i = 0; i < richtext.length; i++) {
    const fragment = richtext.get(i);
    // get the style
    fragment.style('bold');
    // get many styles
    fragment.style(['bold', 'italic']);
    // set one style
    fragment.style('bold', true);
    // get the value
    fragment.value();
    // set the value
    fragment.value('hello');
}

// remove the first rich text fragment
richtext.remove(0);

// clear this rich texts
richtext.clear();
```

How to set a cell to rich texts:
```js
const RichText = require('xlsx-Populate').RichText;
const cell = workbook.sheet(0).cell('A1');
// set a cell value to rich text
const richtext = new RichText();
cell.value(richtext)

// add two rich text fragments
cell.value()
    .add('hello ', { italic: true, bold: true })
    .add('world!', { fontColor: 'FF0000' });
````

You can specify the index when adding rich text fragment.
```js
// add before the first fragment
cell.value().add('text', { bold: true }, 0);
// add before the second fragment
cell.value().add('text', { bold: true }, 1);
// add after the last fragment
cell.value().add('text', { bold: true });
```
#### Notes on how we handle rich texts
We make a deep copy of the richtext instance when assign it to a cell, which
means you can only modify the content of the richtext before calling `cell.value(richtext)`. 
Any modification to the richtext instance after calling `cell.value(richtext)` will not
save to the cell. i.e.
```js
const richtext = new RichText();
richtext.add('hello');
cell.value(richtext);
cell.value().text(); // returns 'hello'

richtext.add(' world')
richtext.text(); // returns 'hello world' 
cell.value().text(); // returns 'hello'
cell.value() === richtext; // returns false

cell.value().add(' world');
cell.value().text(); // returns 'hello world'
```

This means you can create a rich text instance and assign it to any cells! Each cell does
not share the same instance but creates a deep copy of the instance.
```js
const sheet = workbook.sheet(0);
const richtext = new RichText();
richtext.add('hello');
const range = sheet.range("A1:C3");
range.value(richtext);
// they do not share the same instance
sheet.cell('A1').value() === sheet.cell('C1').value() // returns false
```

You can get the rich text from a cell and set it to anoher cell.
```js
const richtext = cell1.value();
cell2.value(richtext);
cell1.value() === cell2.value() // returns false
```

Whenever you call `richtext.add(text, styles, index)`, we will detect if the given `text`
contains line separators (`\n`, `\r`, `\r\n`), if it does, we will call
cell.style('wrapText', true) for you. MS Excel needs wrapText to be true
to have the new lines displayed, otherwise you will see the texts in one line.
You may also need to set row height to have all lines displayed.
```js
cell.value()
    // it support all line separators
    .add('123\n456\r789\r\n10', { italic: true, fontColor: '123456' })
// remember to set height to show the whole row
workbook.sheet(0).row(1).height(100);
```

**Comment by ChaoLiou** [comment]
Hi! 
First of all, thanks you guys for these contributions.
And may i ask: Is this Richtext feature available? 
thanks again

**Comment by LesterLyu** [comment]
You try it out by `npm install https://github.com/LesterLyu/xlsx-populate.git#beta`

**Pull request merged**
