### PR TITLE
Add shared formulas

### PR DESCRIPTION
**Pull request by eddiecorrigall**
Major changes:
    Cell.getRelativeCell
    Cell.setFormula
    Cell.isSharedFormula
    Cell.shareFormulaUntil
    Added demo for shared formulas

### CODE REVIEW

**Comment by eddiecorrigall** [comment]
This will allow programmer to dynamically update a chart from a template, see example.

**Comment by eddiecorrigall** [comment]
@dtjohnson take your time reviewing this, I know its a big update. There will need to be some unit tests added. And once this is ready for merging, we can generate the new docs and merge.

**Comment by dtjohnson** [comment]
Thanks, Eddie! This looks mostly good to me! Does the shared formula just improve performance so it doesn't copy the formula? Or are there other benefits?

A few comments:
- You are missing docs on the last 3 methods in utils.js.
- Does the Cell.isSharedFormula method need to be public? Is that something the users of the library would need?
- You shouldn't be logging to the console. That doesn't play well with various logging frameworks folks might use as they'll be ignored. If you want to add more info to the error messages you should just add them to the Error message.
- You should regen the docs.

**Comment by eddiecorrigall** [comment]
Hi Dave,

I made the suggested changes. We might want to be able to expose _isSharedFormula in some way as in a function to return the cell type: shared formula, shared array, formula, number, string, etc. For now I have made it a private member of cell.

Docs are generated. I added myself as one of the contributors too.

**Comment by eddiecorrigall** [comment]
Hey Dave, according to open office technical write-up of xlsx, shared formulas do offer a performance boost. I'll share this document when I'm back at my computer. Also, the formula can be updated in a single place, so there wouldn't be any need to update the formula anywhere else. Imagine that a template is setup so that it does vector operations. One would simply change the shared formulas for each vector, or matrix. There is much less work involved by the program to update this document. If I can remember, I'll try to make a template like this with an example.

**Comment by dtjohnson** [comment]
Eddie, this is great! I love the solution with the debug module. I didn't know that existed!

**Pull request merged**
