### PR TITLE
Ability to set tooltip for hyperlink

### PR DESCRIPTION
**Pull request by kalexey89**
Hail!

In MS Excel it is possible to set a screen tip for a hyperlink. Pull-request adds a similar capability to xlsx-populate.

Thanks!

### CODE REVIEW

**Comment by dtjohnson** [comment]
PR looks good. Thanks! Could you please add a unit test for the case you added? Then I'll merge and publish.

**Comment by eddiecorrigall** [comment]
Hi @kalexey89, I'd like to merge this, but I'd like to know why there are so many whitespace changes in  README.md. Did you use gulp to generate this or did you manually edit the file?

**Comment by kalexey89** [comment]
> Hi @kalexey89, I'd like to merge this, but I'd like to know why there are so many whitespace changes in README.md. Did you use gulp to generate this or did you manually edit the file?

Hi @eddiecorrigall. Don't remember exactly, it was almost six months ago. But looks like you're right - I edited it by hands. Sorry.

**Comment by eddiecorrigall** [comment]
Hey no problem man, thanks for contributing to the project!

**Comment by eddiecorrigall** [comment]
Under [gulp tasks](https://github.com/dtjohnson/xlsx-populate#gulp-tasks) you can build documentation using `gulp docs` so you wont have to manually update the README.md

**Comment by kalexey89** [comment]
> Under [gulp tasks](https://github.com/dtjohnson/xlsx-populate#gulp-tasks) you can build documentation using `gulp docs` so you wont have to manually update the README.md

@eddiecorrigall , must I generate README.md with gulp task or you can merge this pr as is?

**Comment by eddiecorrigall** [comment]
Yes please, can you run the gulp command to generate the docs?

**Comment by kalexey89** [comment]
> Yes please, can you run the gulp command to generate the docs?

@eddiecorrigall, no problem! I edited hyperlinks example in template.md and make new README.md.

**Comment by eddiecorrigall** [comment]
Going to merge to feature branches for hyperlinks to resolve, then I'll push new feature release to master.

**Comment by eddiecorrigall** [comment]
#175

**Comment by kalexey89** [comment]
Thanks!

**Pull request merged**
