### PR TITLE
Patch print options and page margins

### PR DESCRIPTION
**Pull request by eddiecorrigall**
Original code made a lot of assumptions and was not thoroughly tested.

Introduced new method Sheet.pageMarginsPreset as a convenience for developer.

Discovered:
- A printOptions attribute defined indicates enabled regardless of value, otherwise the attribute is missing and assumed to be disabled by Excel.
- pageMargins is a complex feature. Excel will fail to open a file with a sheet without all attributes defined for pageMargins.

### CODE REVIEW

**Comment by eddiecorrigall** [comment]
@LesterLyu, if you could help review this, I'd very much appreciate your input.

**Comment by eddiecorrigall** [comment]
I will be adding a few e2e tests as soon as I can.

**Comment by eddiecorrigall** [comment]
@LesterLyu do you run Windows at home? Could you possibly write a simple e2e-generate test?

**Comment by LesterLyu** [comment]
I use Windows, I'll see what I can do.

**Comment by LesterLyu** [comment]
I ran the e2e-generate tests. There are **3** tests failed in version 1.19.0. After applying your patch, only one test failed:

```sh
E:\xlsx-populate>npm run e2e-generate

> xlsx-populate@1.19.0 e2e-generate E:\xlsx-populate
> jasmine JASMINE_CONFIG_PATH=test/e2e-generate/jasmine.json

Randomized with seed 16545
Started
.....F

Failures:
1) e2e-generate ./preserve-existing/
  Message:
    {
      chart: {
        height: 216 => 207
        top: 29.62495994567871 => 29.024961471557617
      },
      comments: {
        hidden: {
          height: 59.25 => 57
          left: 59.25 => 58.79999923706055
          top: 16.5 => 15.600000381469727
        },
        visible: {
          height: 131.25 => 126
          left: 131.25 => 130.8000030517578
          top: 125.25 => 120
        }
      },
      image: {
        height: 111 => 106.80000305175781
        top: 21.75 => 21.149999618530273
      }
    }
  Stack:
    Error: {
      chart: {
        height: 216 => 207
        top: 29.62495994567871 => 29.024961471557617
      },
      comments: {
        hidden: {
          height: 59.25 => 57
          left: 59.25 => 58.79999923706055
          top: 16.5 => 15.600000381469727
        },
        visible: {
          height: 131.25 => 126
          left: 131.25 => 130.8000030517578
          top: 125.25 => 120
        }
      },
      image: {
        height: 111 => 106.80000305175781
        top: 21.75 => 21.149999618530273
      }
    }
        at <Jasmine>
        at Promise.resolve.then.then.then.then.then.results (E:\xlsx-populate\test\e2e-generate\e2e-generate.spec.js:54:37)
```

The differences are not much. I'm using the latest version of Excel, it may handle the numbers differently, which may causes the test fails.

**Comment by LesterLyu** [comment]
I cannot push to your branch, please check the tests here: https://github.com/LesterLyu/xlsx-populate/tree/eddie.corrigall/issue-178

**Comment by eddiecorrigall** [comment]
Thanks for that @LesterLyu, I'm not sure what to make of the errors, they don't seem to be related. I only wrote e2e-parse tests. I wonder if you get the same errors when you checkout 1.18.0, or an earlier version, and run them again.

**Comment by LesterLyu** [comment]
Sure, I will check it later.

**Comment by eddiecorrigall** [comment]
@LesterLyu thanks for your help on this. Do you think its finally ready to ship?

**Comment by LesterLyu** [comment]
Yes, all good.

**Pull request merged**
