### PR TITLE
Added initial core properties

### LINKED ISSUE #118: Add file properties
First of all, thank you so much for this module. If you need help with anything related just say it, I'll gladly help.

Second, the API is awesome! Everything is there, just one **minor** thing you could add. This is not that important but would make your module (at least for me) feature-complete. Add an option to add properties to the workbook, most notably:

- Title
- Author
- Keywords / Description

### PR DESCRIPTION
**Pull request by dresende**
If you want any change just comment below 😄 

This allows you to add file properties like **Title** or **Author**.

### Usage

```js
workbook.property("title", "A nice title");

// property names are case insensitive
workbook.property({
    Subject : "Trees",
    Keywords : "tree leaf stalk"
});

console.log(workbook.property("keywords"));
```

Alternative:

```js
let props = workbook.properties();

props.set("Keywords", "tree leat stalk");

console.log(props.get("keywords"));
```

### Allowed Properties

- Title
- Subject
- Creator
- Author (alias for Creator)
- Description
- Keywords
- Category

Closes #118.

### CODE REVIEW

**Comment by dtjohnson** [comment]
This is very pretty code! Thanks for the contribution. The only thing missing is unit tests for the CoreProperties class and Workbook.property.

**Comment by dresende** [comment]
Added test. I have no way of resolving the conflicting files.

**Comment by dtjohnson** [comment]
Don't worry about conflicts in the built files.

**Comment by dtjohnson** [comment]
Published in v1.15.0

**Pull request merged**
