### PR TITLE
Update version

### PR DESCRIPTION
**Pull request by Climber22**
# WHAT
 - Revise description for updating the version of this package.

# WHY
I created PR #169  but I've forgotten updating the version.
So I created this PR.
If it's not suitable for me to add this description, you can close this PR.

### CODE REVIEW

**Comment by eddiecorrigall** [comment]
Yes good idea, please update `package-lock.json` too, for example: https://github.com/dtjohnson/xlsx-populate/commit/958275ef3b3bdd1d249758de1e04c9af8be2ba2b

Also, please update to **1.17.1** instead.

Versioning format typically follows `{major}.{minor}.{fix}` where major indicates breaking changes, minor indicates a feature change with no breaking changes (ie. new features), and fix is incremented when bugs are corrected to make existing features work.

**Comment by Climber22** [comment]
@eddiecorrigall 
Thank you for your explanation !
I fixed.

**Comment by eddiecorrigall** [comment]
@Climber22, we might need to have Dave update/publish the version change on npm.

**Comment by Climber22** [comment]
@eddiecorrigall 
oops, I forgot that one.

All what I have to do is run 2 commands below at my local repo?
```
npm version patch
npm publish ./
```

**Comment by eddiecorrigall** [comment]
I think you'll find that you do not have user permissions. I tried something similar. Ill send Dave an email.

**Comment by eddiecorrigall** [comment]
I now have a npm account, Dave gave me permissions to publish. I have pushed 1.17.1 😄

**Comment by Climber22** [comment]
Thanks a lot !!

**Comment by eddiecorrigall** [comment]
Not to self:
```
npm version {major}.{minor}.{fix}
npm publish .
```

**Pull request merged**
