### PR TITLE
Added dataValidation Support

### PR DESCRIPTION
**Pull request by alandoyle95**
OK, after several hours. i think i got this working pretty well. the getter/setter is working, let me know if there are any improvements you want :P

### CODE REVIEW

**Comment by dtjohnson** [comment]
At first glance this looks really good. Obviously we'll need some test coverage, but let me pull this down locally and do a more thorough review.

**Comment by alandoyle95** [comment]
awesome :D that makes me super happy to hear haha

**Comment by dtjohnson** [comment]
OK. I reviewed this in-depth. From an architecture perspective it's spot on. I would've designed the methods in the exact same way. It also passes all of the tests including the E2E ones that make sure you aren't breaking existing workbooks. Well done!

There are a number of updates we'd need to make to get this ready for merging and publishing:
- All three methods could use some cleanup of the JSDoc. It's used to generate the API documentation in the README so it's important that it is clear and well-written. We should also add a table for the DataValidation object in the README like Style to show the user what all of the various properties and values are. And the setter for `Sheet.dataValidation` should be `@ignore`'d as well.
- Are there any shortcut overloads we should add? Like using an array of strings will set the validation to a pick list?
- It should be clear from the `Range.dataValidation` documentation that this gets/sets the data validation for the entire range and not just a collection of all of the cell data validations (like value).
- There are a few ESLint errors in `Sheet.dataValidation`. You can run `gulp lint` to see them or configure your IDE (if applicable) to show them.
- We need to make sure we're considering *all* options for data validation. In a quick test I see we are missing `errorTitle`, `prompt`, `promptTitle`, and `formula2`. A suggestion to future-proof would be to just make a copy of the `obj` variable to set as the attributes but remove `formula1` and `formula2`. Right now calling `cell.dataValidation(cell.dataValidation())` will result in data loss for many cases.
- The getters return the boolean values like `allowBlank` as a 1 or 0 as that is how the XML is encoded. I'd much prefer an actual boolean to make the API more natural. We could just convert between 1/0 and true/false in the getter/setters like we do for Styles.
- In the same vein, it might be nice to make the `formula1` and `formula2` named in a more useful way depending on the type. So if type is 'whole' you would use the properties `minimum` and `maximum` instead to make it more friendly and match the Excel UI. I did a lot of this in Style.js.
- We'll need full unit test coverage for these new methods. There are loads of examples. You can run `gulp` to run the tests and watch for changes.
- We should probably add some basic E2E generation test coverage to make sure we're creating these correctly. These E2E test do require a Windows computer with Excel and .NET though.

**Comment by alandoyle95** [comment]
Ok I will attempt to do some of those things haha, don't even know what half of that is.. like I said, super new to the whole node programming thing, and super super new to programming with other people's code styles and documentation style xD didn't even know you could generate the documentation automatically haha.

**Comment by alandoyle95** [comment]
seems my IDE decided to space stuff on that one... huh weird...

**Comment by dtjohnson** [comment]
Sorry for the delay; things have been hectic at work lately. The updates all look great! I have just 3 more requests before I merge, if you don't mind.
1. There are 12 ESLint errors in Sheet.js. If you run "gulp lint" you'll see them.
2. Could we add a table of documentation for the DataValidation object so folks know what values to expect? Just add another section after Style Reference at the bottom of docs/template.md.
3. Add yourself as a contributor in package.json. :)

Thanks!

**Comment by dtjohnson** [comment]
Also, we need to add unit test coverage for all of these methods before we can released.

**Comment by alandoyle95** [comment]
I fixed all the ESLint errors, but it also complained about me returning `true` or `false` when getting a DataValidation object, so I removed them to fix the errors, but I know you talked about having it not return `0` or `1` but return `true` or `false`

not sure if you still want that to be the case, as far as the `README` do I just add the block in the table of contents and then the corresponding block below ? or do you want me to add all of the docs?

**Comment by alandoyle95** [comment]
Just noticed you said the bottom of the docs.... Want me to move them?

I also did a little of an addition for a shortcut as well. I looked at the test folder.. and I'm not sure how I would go about adding in a test for dataValidation.. any explanation on how to go about doing that?

**Comment by alandoyle95** [comment]
Hope all is going well with work XD haha let me know when you get time if the changes are good, if not I'll do my best to fix them

**Comment by dtjohnson** [comment]
Cool! The list shortcut looks great! And the ESLint fixes look good.

The only thing missing is tests. If you look in the test/unit folder you'll see a .spec.js file for each file in lib. These are [Jasmine](https://jasmine.github.io/) unit test scripts. You'll need to create a `describe` block for each method you added and then add at least one `it` block to assert that the behavior is correct. You can see the pattern from the other tests. If you run `gulp` from a command line the tests will be continuously rerun why you modify them and the source code.

**Comment by alandoyle95** [comment]
Alright awesome, i'll look into that tonight hopefully.

**Comment by alandoyle95** [comment]
is there a way to say...

`expect(cell.dataValidation()).toBeObject();`

**Comment by dtjohnson** [comment]
Nope, but you can use `toEqualJson` to compare to an expected object structure. See [this line](https://github.com/dtjohnson/xlsx-populate/blob/15c6fcf19d23d909338c8968960b30793eb08766/test/unit/Cell.spec.js#L337) for example.

**Comment by alandoyle95** [comment]
Oh, well that will do what I wanted :D

**Comment by alandoyle95** [comment]
how does that test look ? (its not in the right area.. its at the beginning of the file, i was going to put it after the hyper-link tests to keep with the spec, and it also does not do verification of the json yet)

**Comment by alandoyle95** [comment]
ok... so I'm only having one issue.. and I'm not sure why, but I feel like its due to the tests. 

```
        let cell = workbook.sheet('Sheet1').cell('A1');
        console.log('false: ', cell.dataValidation());
        cell.dataValidation('test1, test2, test3');
        console.log('Json: ', cell.dataValidation());
        console.log('true : ', cell.dataValidation(false));
        console.log('false: ', cell.dataValidation());
```

but if i do that with the tests..

```
it('should return false', () => {
            expect(cell.dataValidation()).toBe(false);
        })

it('should return the cell', () => {
            expect(cell.dataValidation({ type: 'list',
                allowBlank: false,
                showInputMessage: false,
                prompt: '',
                promptTitle: '',
                showErrorMessage: false,
                error: '',
                errorTitle: '',
                operator: '',
                formula1: 'test1, test2, test3',
                formula2: ''
            })).toBe(cell);
        })


it('should return JSON object', () => {
            expect(cell.dataValidation()).toEqualJson({ type: 'list',
                allowBlank: false,
                showInputMessage: false,
                prompt: '',
                promptTitle: '',
                showErrorMessage: false,
                error: '',
                errorTitle: '',
                operator: '',
                formula1: 'test1, test2, test3',
                formula2: ''
            });
        })

 it('should return true', () => {
            expect(cell.dataValidation(false)).toBe(true);
        })

 it('should return true', () => {
            expect(cell.dataValidation(false)).toBe(false);
        })
```


i get this from the normal test that i ran first.


```
false:  false

Json:  {
  type: 'list',
  allowBlank: false,
  showInputMessage: false,
  prompt: '',
  promptTitle: '',
  showErrorMessage: false,
  error: '',
  errorTitle: '',
  operator: '',
  formula1: 'test1, test2, test3',
  formula2: ''
}

true :  true

false:  false

```

but the unit tests..
```

Failures:
1) Cell dataValidation should return false
  Message:
    Expected undefined to be false.
  Stack:
    Error: Expected undefined to be false.
        at UserContext.it (/code/Node/xlsx-populate/test/unit/Cell.spec.js:203:43)
        at runCallback (timers.js:672:20)
        at tryOnImmediate (timers.js:645:5)
        at processImmediate [as _immediateCallback] (timers.js:617:5)
    

2) Cell dataValidation should return JSON object
  Message:
    SyntaxError: Unexpected token u in JSON at position 0
  Stack:
    SyntaxError: Unexpected token u in JSON at position 0
        at Object.parse (native)
        at compare (/code/Node/xlsx-populate/test/helpers/toEqualJson.js:11:35)
        at UserContext.it (/code/Node/xlsx-populate/test/unit/Cell.spec.js:211:43)
        at ontimeout (timers.js:386:14)
        at tryOnTimeout (timers.js:250:5)
        at Timer.listOnTimeout (timers.js:214:5)
    

3) Cell dataValidation should return true
  Message:
    Expected undefined to be true.
  Stack:
    Error: Expected undefined to be true.
        at UserContext.it (/code/Node/xlsx-populate/test/unit/Cell.spec.js:227:48)
        at runCallback (timers.js:672:20)
        at tryOnImmediate (timers.js:645:5)
        at processImmediate [as _immediateCallback] (timers.js:617:5)
    

4) Cell dataValidation should return JSON object
  Message:
    SyntaxError: Unexpected token u in JSON at position 0
  Stack:
    SyntaxError: Unexpected token u in JSON at position 0
        at Object.parse (native)
        at compare (/code/Node/xlsx-populate/test/helpers/toEqualJson.js:11:35)
        at UserContext.it (/code/Node/xlsx-populate/test/unit/Cell.spec.js:246:43)
        at runCallback (timers.js:672:20)
        at tryOnImmediate (timers.js:645:5)
        at processImmediate [as _immediateCallback] (timers.js:617:5)
    

5) Cell dataValidation should return true
  Message:
    Expected undefined to be true.
  Stack:
    Error: Expected undefined to be true.
        at UserContext.it (/code/Node/xlsx-populate/test/unit/Cell.spec.js:261:48)
        at runCallback (timers.js:672:20)
        at tryOnImmediate (timers.js:645:5)
        at processImmediate [as _immediateCallback] (timers.js:617:5)

```

**Comment by alandoyle95** [comment]
@dtjohnson  any support on the tests ? or should i just simplify the tests it does ? i was hoping to have it test all the features though.

**Comment by dtjohnson** [comment]
Hey @alandoyle95, the Range and Cell setter tests look good! You'll notice that the Sheet class gets mocked with a Jasmine spy in the test setup. This is because the unit tests are just testing the individual classes. So your Cell tests should just test behavior in Cell, not Sheet. All you want to test in Cell is that it is making the correct calls to Sheet and returning the correct values.

You should also add a quick test to make sure the Call/Range dataValidation getters work well too. You should have the mock Sheet.dataValidation return some dummy value (like [this](https://github.com/dtjohnson/xlsx-populate/blob/15c6fcf19d23d909338c8968960b30793eb08766/test/unit/Cell.spec.js#L36)) and then expect that if you call your getter it will return that value (like [this](https://github.com/dtjohnson/xlsx-populate/blob/15c6fcf19d23d909338c8968960b30793eb08766/test/unit/Cell.spec.js#L191)).

You'll also need to add tests on the Sheet.dataValidation, toXmls, and _inits methods. For the getter in your dataValidation method, you'll need to simply manually set the data in your _dataValidations property and then write expectations against the method call. For the setters, you call the method first and then write expectations against the value stored in _dataValidations. See the [hyperlinks tests](https://github.com/dtjohnson/xlsx-populate/blob/15c6fcf19d23d909338c8968960b30793eb08766/test/unit/Sheet.spec.js#L624) for an example. You should see similar code you can follow for the _init and toXmls.

**Comment by alandoyle95** [comment]
ahh so its not really "using" the code and setting up a fake xlsx file.. so
you have to tell it what you are going to return.. thats why the getters
where not working, ok that makes a lot more sense now.

**Comment by dtjohnson** [comment]
Exactly. The point of unit tests is to test the behavior of small pieces of
code in isolation. So we replace other classes and functions with
mocks/spies with predefined behavior so we can verify that the code of
interest is behaving correctly.

There are also end-to-end tests in the tests folder that test the full
behavior with real workbooks. Those are slow so they are not run all the
time like the unit tests.

**Comment by alandoyle95** [comment]
OK! i think i got everything in there and it all passes :) so should be good to go, let me know if there is anything else!

**Comment by dtjohnson** [comment]
Fantastic! Merged. I did a little tweaking of the docs. Also, you put the docs in the README.md instead of the docs/template.md file. The README is autogened by gulp to build the ToC and the API reference. I moved it to the right place.

I just published v1.11.0 with your change. Many thanks!

**Comment by alandoyle95** [comment]
Ahh, I'll note that for when I do another feature xD well. If I do haha I
do need image support so I'm going to start to look I to that xD but I'm
not sure of the stored jszip  will allow overrides and it will not care
about a new image size if I just swap and image

**Pull request merged**
