### PR TITLE
add `Sheet.name("new sheet name")`

### PR DESCRIPTION
**Pull request by nitsanavni**

### CODE REVIEW

**Comment by dtjohnson** [comment]
Thanks for sharing! The code looks great. I just have one concern. The XLSX format unfortunately stores the name of the sheets in formula references. So if you reference a cell from another sheet, that reference includes the containing sheet name. So if we rename in this way, all of the formula references would be broken.

I see two ways to approach this:
1. We need to change the names of the sheets in all references. We'd need to have a formula parser and some knowledge of where all of these references might exist in the model.
2. We implement this method as-is, but we'd need to include some strong warning that this will break cross-sheet formulas if they exist. The benefit is that this provides the functionality for those who don't have that issue.

Thoughts?

**Comment by nitsanavni** [comment]
Hmm that _is_ unfortunate :/
Will think about it some more.
FYI for _our_ use case this implementation is currently sufficient.

**Comment by nitsanavni** [comment]
BTW, nice repo with nice fast running tests!

**Comment by dtjohnson** [comment]
Thanks! I expect this would be sufficient for a lot of use cases as well, which makes me lean towards option 2.

**Pull request merged**
